apiVersion: v1
kind: Service
metadata:
  name: parasol-insurance
  namespace: {{ .Values.namespace }}
  labels:
    app: parasol-insurance
    app.kubernetes.io/name: parasol-insurance-secured-{{ .Values.tenant.username }}
    app.kubernetes.io/part-of: parasol-insurance-{{ .Values.environment }}
spec:
  selector:
    app: parasol-insurance
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
